-- Andina: columnas y tablas de las historias de usuario completadas (octubre 2026).
-- Solo AGREGA: no borra tablas, columnas ni datos. Se puede ejecutar más de una vez (IF NOT EXISTS).
-- Ejecutar en Supabase (SQL Editor) ANTES de desplegar el backend nuevo: la API arranca con ddl-auto=validate
-- y no inicia si faltan estas columnas o tablas. El backend anterior sigue funcionando con ellas agregadas.
BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '60s';
SET LOCAL search_path = public;

-- HU30/HU44/HU47: aula actual de la persona (opcional)
ALTER TABLE persona ADD COLUMN IF NOT EXISTS id_aula bigint;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_persona_aula') THEN
        ALTER TABLE persona ADD CONSTRAINT fk_persona_aula FOREIGN KEY (id_aula) REFERENCES aulas (id_aula);
    END IF;
END $$;
CREATE INDEX IF NOT EXISTS ix_persona_id_aula ON persona (id_aula);

-- HU33/HU39/HU46: el perfil académico pertenece a un estudiante y guarda su estado psicológico
ALTER TABLE perfil_academico ADD COLUMN IF NOT EXISTS id_persona bigint;
ALTER TABLE perfil_academico ADD COLUMN IF NOT EXISTS estado_psicologico varchar(100);
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_perfil_academico_persona') THEN
        ALTER TABLE perfil_academico ADD CONSTRAINT fk_perfil_academico_persona FOREIGN KEY (id_persona) REFERENCES persona (id_persona);
    END IF;
END $$;
CREATE UNIQUE INDEX IF NOT EXISTS ux_perfil_academico_id_persona ON perfil_academico (id_persona);

-- HU06: conectividad medida de cada escuela
ALTER TABLE colegios ADD COLUMN IF NOT EXISTS velocidad_bajada_mbps float(53);
ALTER TABLE colegios ADD COLUMN IF NOT EXISTS velocidad_subida_mbps float(53);
ALTER TABLE colegios ADD COLUMN IF NOT EXISTS tipo_conexion varchar(30);
ALTER TABLE colegios ADD COLUMN IF NOT EXISTS fecha_medicion_conectividad date;

-- HU08: asistencia y calificación por alumno y sesión
CREATE TABLE IF NOT EXISTS asistencia (
    id_asistencia bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 MINVALUE 1000) PRIMARY KEY,
    id_persona bigint NOT NULL REFERENCES persona (id_persona),
    id_curso bigint NOT NULL REFERENCES curso (id_curso),
    id_periodo bigint NOT NULL REFERENCES periodos_academicos (id_periodo),
    fecha_sesion date NOT NULL,
    estado varchar(20) NOT NULL,
    calificacion float(53),
    observacion varchar(200),
    CONSTRAINT uk_asistencia_persona_curso_fecha UNIQUE (id_persona, id_curso, fecha_sesion)
);
CREATE INDEX IF NOT EXISTS ix_asistencia_id_periodo ON asistencia (id_periodo);
CREATE INDEX IF NOT EXISTS ix_asistencia_id_curso ON asistencia (id_curso);

-- HU11: convenios con gobiernos regionales y cooperación
CREATE TABLE IF NOT EXISTS convenio (
    id_convenio bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 MINVALUE 1000) PRIMARY KEY,
    nombre varchar(200) NOT NULL,
    entidad varchar(200) NOT NULL,
    tipo_entidad varchar(50) NOT NULL,
    region varchar(50) NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    presupuesto numeric(14, 2) NOT NULL,
    estado varchar(20) NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_convenio_fecha_fin ON convenio (fecha_fin);

-- HU13: capacitación en competencias digitales docentes
CREATE TABLE IF NOT EXISTS capacitacion_docente (
    id_capacitacion bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 MINVALUE 1000) PRIMARY KEY,
    id_persona bigint NOT NULL REFERENCES persona (id_persona),
    modulo varchar(100) NOT NULL,
    puntaje float(53),
    fecha_evaluacion date,
    estado varchar(20) NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_capacitacion_docente_id_persona ON capacitacion_docente (id_persona);

-- HU14: incidencias técnicas
CREATE TABLE IF NOT EXISTS incidencia (
    id_incidencia bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 MINVALUE 1000) PRIMARY KEY,
    id_persona bigint NOT NULL REFERENCES persona (id_persona),
    id_colegio bigint REFERENCES colegios (id_colegio),
    titulo varchar(150) NOT NULL,
    descripcion varchar(1000) NOT NULL,
    prioridad varchar(20) NOT NULL,
    estado varchar(20) NOT NULL,
    afecta_sesion boolean NOT NULL DEFAULT false,
    fecha_reporte timestamp(6) NOT NULL,
    fecha_cierre timestamp(6)
);
CREATE INDEX IF NOT EXISTS ix_incidencia_id_persona ON incidencia (id_persona);
CREATE INDEX IF NOT EXISTS ix_incidencia_id_colegio ON incidencia (id_colegio);
CREATE INDEX IF NOT EXISTS ix_incidencia_prioridad_estado ON incidencia (prioridad, estado);

-- HU15: bitácora de accesos y cambios (solo inserción)
CREATE TABLE IF NOT EXISTS auditoria (
    id_auditoria bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 MINVALUE 1000) PRIMARY KEY,
    fecha_hora timestamp(6) NOT NULL,
    usuario varchar(50),
    modulo varchar(50) NOT NULL,
    accion varchar(30) NOT NULL,
    detalle varchar(300),
    ip varchar(45),
    estado_http integer
);
CREATE INDEX IF NOT EXISTS ix_auditoria_fecha_hora ON auditoria (fecha_hora);
CREATE INDEX IF NOT EXISTS ix_auditoria_usuario_fecha ON auditoria (usuario, fecha_hora);
CREATE INDEX IF NOT EXISTS ix_auditoria_accion_fecha ON auditoria (accion, fecha_hora);

-- La bitácora es inmutable también en la base: se rechaza cualquier UPDATE, DELETE o TRUNCATE
CREATE OR REPLACE FUNCTION auditoria_inmutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'La bitácora de auditoría no se puede modificar ni borrar';
END $$;
DROP TRIGGER IF EXISTS tr_auditoria_inmutable ON auditoria;
CREATE TRIGGER tr_auditoria_inmutable BEFORE UPDATE OR DELETE ON auditoria
    FOR EACH ROW EXECUTE FUNCTION auditoria_inmutable();
DROP TRIGGER IF EXISTS tr_auditoria_sin_truncate ON auditoria;
CREATE TRIGGER tr_auditoria_sin_truncate BEFORE TRUNCATE ON auditoria
    FOR EACH STATEMENT EXECUTE FUNCTION auditoria_inmutable();

-- HU16: encuestas de satisfacción y sus respuestas
CREATE TABLE IF NOT EXISTS encuesta (
    id_encuesta bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 MINVALUE 1000) PRIMARY KEY,
    titulo varchar(150) NOT NULL,
    descripcion varchar(500),
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    estado varchar(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS respuesta_encuesta (
    id_respuesta bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1000 MINVALUE 1000) PRIMARY KEY,
    id_encuesta bigint NOT NULL REFERENCES encuesta (id_encuesta),
    id_persona bigint NOT NULL REFERENCES persona (id_persona),
    satisfaccion_general integer NOT NULL,
    calidad_contenido integer NOT NULL,
    facilidad_uso integer NOT NULL,
    comentario varchar(500),
    fecha_respuesta timestamp(6) NOT NULL,
    CONSTRAINT uk_respuesta_encuesta_persona UNIQUE (id_encuesta, id_persona)
);
CREATE INDEX IF NOT EXISTS ix_respuesta_encuesta_id_persona ON respuesta_encuesta (id_persona);

-- Igual que las demás tablas del proyecto: RLS activo (la API usa su propia conexión PostgreSQL)
ALTER TABLE asistencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE convenio ENABLE ROW LEVEL SECURITY;
ALTER TABLE capacitacion_docente ENABLE ROW LEVEL SECURITY;
ALTER TABLE incidencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE auditoria ENABLE ROW LEVEL SECURITY;
ALTER TABLE encuesta ENABLE ROW LEVEL SECURITY;
ALTER TABLE respuesta_encuesta ENABLE ROW LEVEL SECURITY;

COMMIT;
